my_dbt_project:
  outputs:
    dev:
      dataset: newsletter
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: C:\Users\sreej\.google\credentials\google_credentials.json
      location: US
      method: service-account
      priority: interactive
      project: de-project-batch
      threads: 1
      type: bigquery
  target: dev
