name: dbt CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dbt-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List repository structure
        run:  |
          echo "Repository structure:"
          find . | awk -F/ 'NF<=1' | sort


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install dbt-core dbt-bigquery google-cloud-bigquery

      - name: Install dbt dependencies
        working-directory: my_dbt_project
        run: dbt deps

      - name: Run dbt models
        working-directory: my_dbt_project
        run: dbt run

      - name: Run dbt tests
        working-directory: my_dbt_project
        run: dbt test

      - name: Generate dbt docs
        working-directory: my_dbt_project
        run: dbt docs generate
